[package]
name = "book_library_server"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "prisma-cli"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"

prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.9", default-features = false, features = ["postgresql"] }

tokio = { version = "1.32.0", features = ["full"] }

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"]}
tower-http = { version = "0.4.4", features = ["trace"] }

axum = { version = "0.6.20", features = ["json"] }
axum-extra = { version ="0.8.0", features = ["query"] }
axum-prometheus = "0.4.0"
serde = { version = "1.0.188", features = ["derive"] }

sentry = { version = "0.31.7", features = ["debug-images"] }

meilisearch-sdk = "0.24.2"

rand = "0.8.5"

chrono = "0.4.31"
