[package]
name = "book_library_server"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "prisma-cli"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"

prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11", default-features = false, features = ["postgresql"] }

tokio = { version = "1.36.0", features = ["full"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
tower-http = { version = "0.5.1", features = ["trace"] }

axum = { version = "0.7.4", features = ["json"] }
axum-extra = { version ="0.9.2", features = ["query"] }
axum-prometheus = "0.6.1"
serde = { version = "1.0.196", features = ["derive"] }

sentry = { version = "0.32.2", features = ["debug-images"] }

meilisearch-sdk = "0.24.3"

rand = "0.8.5"

chrono = "0.4.33"
