"""empty message

Revision ID: 08193b547a80
Revises: b44117a41998
Create Date: 2021-11-19 14:04:16.589304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08193b547a80'
down_revision = 'b44117a41998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_sequences_name'), 'sequences', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequences_name'), table_name='sequences')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    # ### end Alembic commands ###
