"""empty message

Revision ID: 08193b547a80
Revises: b44117a41998
Create Date: 2021-11-19 14:04:16.589304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08193b547a80"
down_revision = "b44117a41998"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.create_index(
        op.f("ix_books_is_deleted"),
        "books",
        [sa.text("is_deleted = 'f'")],
        unique=False,
    )
    op.create_index(op.f("ix_books_file_type"), "books", ["file_type"], unique=False)
    op.create_index(op.f("ix_sequences_name"), "sequences", ["name"], unique=False)
    op.create_index(
        op.f("tgrm_books_title"),
        "books",
        ["title"],
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("tgrm_sequences_name"),
        "sequences",
        ["name"],
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("tgrm_authors_lfm"),
        "authors",
        [sa.text("(last_name || ' ' || first_name || ' ' || middle_name)")],
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("tgrm_authors_lf"),
        "authors",
        [sa.text("(last_name || ' ' || first_name)")],
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("tgrm_authors_l"),
        "authors",
        ["last_name"],
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("book_authors_book"),
        "book_authors",
        ["book"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        op.f("book_authors_author"),
        "book_authors",
        ["author"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        op.f("book_sequences_book"),
        "book_sequences",
        ["book"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        op.f("book_sequences_sequence"),
        "book_sequences",
        ["sequence"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        op.f("translations_book"),
        "translations",
        ["book"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        op.f("translations_author"),
        "translations",
        ["author"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        op.f("book_genres_book"),
        "book_genres",
        ["book"],
        unique=False,
        postgresql_using="btree",
    ),
    op.create_index(
        op.f("book_genres_genre"),
        "book_genres",
        ["genre"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sequences_name"), table_name="sequences")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_index(op.f("ix_books_is_deleted"), table_name="books")
    op.drop_index(op.f("ix_books_file_type"), table_name="books")
    op.drop_index(op.f("tgrm_books_title"), table_name="books")
    op.drop_index(op.f("tgrm_sequences_name"), table_name="books")
    op.drop_index(op.f("tgrm_authors_lfm"), table_name="books")
    op.drop_index(op.f("tgrm_authors_lf"), table_name="books")
    op.drop_index(op.f("tgrm_authors_l"), table_name="books")
    op.drop_index(op.f("book_authors_book"), table_name="book_authors")
    op.drop_index(op.f("book_authors_author"), table_name="book_authors")
    op.drop_index(op.f("book_sequences_book"), table_name="book_sequences")
    op.drop_index(op.f("book_sequences_sequence"), table_name="book_sequences")
    op.drop_index(op.f("translations_book"), table_name="translations")
    op.drop_index(op.f("translations_author"), table_name="translations")
    op.drop_index(op.f("book_genres_book"), table_name="book_genres"),
    op.drop_index(op.f("book_genres_genre"), table_name="book_genres"),
    # ### end Alembic commands ###
