"""empty message

Revision ID: 6d0dbf1e4998
Revises: 9c4b98440632
Create Date: 2021-11-07 20:23:39.656518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0dbf1e4998'
down_revision = '9c4b98440632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_sequence_infos_sequence_position', 'sequence_infos', ['sequence', 'position'])
    op.create_unique_constraint('uc_translations_book_position', 'translations', ['book', 'position'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_translations_book_position', 'translations', type_='unique')
    op.drop_constraint('uc_sequence_infos_sequence_position', 'sequence_infos', type_='unique')
    # ### end Alembic commands ###
