name: Build docker image

on:
  push:
    branches:
      - "main"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  Build-Docker-Image:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - id: repository_name
        uses: ASzc/change-string-case-action@v8
        with:
          string: ${{ github.repository }}

      - name: Login to ghcr.io
        uses: docker/login-action@v4.5.2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v7
        env:
          IMAGE: ${{ steps.repository_name.outputs.lowercase }}
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ env.IMAGE }}:latest,ghcr.io/${{ env.IMAGE }}:${{ github.sha }}
          context: .
          file: ./docker/build.dockerfile

      - name: Invoke deployment hook
        run: curl -sf -X POST "${{ secrets.WEBHOOK_URL }}?BOOK_SERVER_TAG=${{ github.sha }}"
