name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry/target
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-features -- -D warnings
        env:
          SQLX_OFFLINE: "true"

      - name: Test
        run: cargo test --all-features
        env:
          SQLX_OFFLINE: "true"
